### ISSUE TITLE
Projects are not latest!

### ISSUE THREAD

**Issue by narayananpalani** [narayananpalani/testautomation#2]
Latest Projects are left over more than a week now! No Maven projects uploaded (except Jeyabala). Joe's projects not reflected in Git. No latest projects from Arrchana,Haroon,Usman and Shivani as well

**Comment by narayananpalani** [comment]
Why the projects are not uploaded after raising this issue-Its been more than 7days ago!

**Comment by HaroonVicapri** [comment]
Sir what is Maven project? I forgot. I'm trying to figure out how to add
commit and push my job project.

**Comment by narayananpalani** [comment]
Please make sure that the POM file what is designed during maven project (check with Usman if possible), along with Projects such as Job Portal Automation has to be uploaded from everyone.
